// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: R2A_SenSorData.proto

package com.sasa5680.ProtoMessages.R2A;

public final class R2ASenSorData {
  private R2ASenSorData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface R2A_SenSorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:R2A_SenSorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string GPS = 2;</code>
     */
    java.lang.String getGPS();
    /**
     * <code>string GPS = 2;</code>
     */
    com.google.protobuf.ByteString
        getGPSBytes();

    /**
     * <code>float battery = 3;</code>
     */
    float getBattery();

    /**
     * <code>float altitude = 4;</code>
     */
    float getAltitude();
  }
  /**
   * Protobuf type {@code R2A_SenSorData}
   */
  public  static final class R2A_SenSorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:R2A_SenSorData)
      R2A_SenSorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use R2A_SenSorData.newBuilder() to construct.
    private R2A_SenSorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private R2A_SenSorData() {
      gPS_ = "";
      battery_ = 0F;
      altitude_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private R2A_SenSorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              gPS_ = s;
              break;
            }
            case 29: {

              battery_ = input.readFloat();
              break;
            }
            case 37: {

              altitude_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.internal_static_R2A_SenSorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.internal_static_R2A_SenSorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.class, com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.Builder.class);
    }

    public static final int GPS_FIELD_NUMBER = 2;
    private volatile java.lang.Object gPS_;
    /**
     * <code>string GPS = 2;</code>
     */
    public java.lang.String getGPS() {
      java.lang.Object ref = gPS_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gPS_ = s;
        return s;
      }
    }
    /**
     * <code>string GPS = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGPSBytes() {
      java.lang.Object ref = gPS_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gPS_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATTERY_FIELD_NUMBER = 3;
    private float battery_;
    /**
     * <code>float battery = 3;</code>
     */
    public float getBattery() {
      return battery_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 4;
    private float altitude_;
    /**
     * <code>float altitude = 4;</code>
     */
    public float getAltitude() {
      return altitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGPSBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gPS_);
      }
      if (battery_ != 0F) {
        output.writeFloat(3, battery_);
      }
      if (altitude_ != 0F) {
        output.writeFloat(4, altitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGPSBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gPS_);
      }
      if (battery_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, battery_);
      }
      if (altitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, altitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData)) {
        return super.equals(obj);
      }
      com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData other = (com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData) obj;

      boolean result = true;
      result = result && getGPS()
          .equals(other.getGPS());
      result = result && (
          java.lang.Float.floatToIntBits(getBattery())
          == java.lang.Float.floatToIntBits(
              other.getBattery()));
      result = result && (
          java.lang.Float.floatToIntBits(getAltitude())
          == java.lang.Float.floatToIntBits(
              other.getAltitude()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GPS_FIELD_NUMBER;
      hash = (53 * hash) + getGPS().hashCode();
      hash = (37 * hash) + BATTERY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBattery());
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAltitude());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code R2A_SenSorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:R2A_SenSorData)
        com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.internal_static_R2A_SenSorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.internal_static_R2A_SenSorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.class, com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.Builder.class);
      }

      // Construct using com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        gPS_ = "";

        battery_ = 0F;

        altitude_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.internal_static_R2A_SenSorData_descriptor;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData getDefaultInstanceForType() {
        return com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.getDefaultInstance();
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData build() {
        com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData buildPartial() {
        com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData result = new com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData(this);
        result.gPS_ = gPS_;
        result.battery_ = battery_;
        result.altitude_ = altitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData) {
          return mergeFrom((com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData other) {
        if (other == com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData.getDefaultInstance()) return this;
        if (!other.getGPS().isEmpty()) {
          gPS_ = other.gPS_;
          onChanged();
        }
        if (other.getBattery() != 0F) {
          setBattery(other.getBattery());
        }
        if (other.getAltitude() != 0F) {
          setAltitude(other.getAltitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object gPS_ = "";
      /**
       * <code>string GPS = 2;</code>
       */
      public java.lang.String getGPS() {
        java.lang.Object ref = gPS_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gPS_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string GPS = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGPSBytes() {
        java.lang.Object ref = gPS_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gPS_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string GPS = 2;</code>
       */
      public Builder setGPS(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gPS_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string GPS = 2;</code>
       */
      public Builder clearGPS() {
        
        gPS_ = getDefaultInstance().getGPS();
        onChanged();
        return this;
      }
      /**
       * <code>string GPS = 2;</code>
       */
      public Builder setGPSBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gPS_ = value;
        onChanged();
        return this;
      }

      private float battery_ ;
      /**
       * <code>float battery = 3;</code>
       */
      public float getBattery() {
        return battery_;
      }
      /**
       * <code>float battery = 3;</code>
       */
      public Builder setBattery(float value) {
        
        battery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float battery = 3;</code>
       */
      public Builder clearBattery() {
        
        battery_ = 0F;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <code>float altitude = 4;</code>
       */
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <code>float altitude = 4;</code>
       */
      public Builder setAltitude(float value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float altitude = 4;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:R2A_SenSorData)
    }

    // @@protoc_insertion_point(class_scope:R2A_SenSorData)
    private static final com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData();
    }

    public static com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<R2A_SenSorData>
        PARSER = new com.google.protobuf.AbstractParser<R2A_SenSorData>() {
      @java.lang.Override
      public R2A_SenSorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new R2A_SenSorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<R2A_SenSorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<R2A_SenSorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sasa5680.ProtoMessages.R2A.R2ASenSorData.R2A_SenSorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_R2A_SenSorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_R2A_SenSorData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024R2A_SenSorData.proto\"@\n\016R2A_SenSorData" +
      "\022\013\n\003GPS\030\002 \001(\t\022\017\n\007battery\030\003 \001(\002\022\020\n\010altitu" +
      "de\030\004 \001(\002B \n\036com.sasa5680.ProtoMessages.R" +
      "2Ab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_R2A_SenSorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_R2A_SenSorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_R2A_SenSorData_descriptor,
        new java.lang.String[] { "GPS", "Battery", "Altitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
