// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2C_AndroidLoading.proto

package com.sasa5680.ProtoMessages.S2C;

public final class S2CAndroidLoading {
  private S2CAndroidLoading() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2C_AndroidLoadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:S2C_AndroidLoading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes androidLoading = 1;</code>
     */
    com.google.protobuf.ByteString getAndroidLoading();
  }
  /**
   * Protobuf type {@code S2C_AndroidLoading}
   */
  public  static final class S2C_AndroidLoading extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:S2C_AndroidLoading)
      S2C_AndroidLoadingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C_AndroidLoading.newBuilder() to construct.
    private S2C_AndroidLoading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C_AndroidLoading() {
      androidLoading_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C_AndroidLoading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              androidLoading_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.internal_static_S2C_AndroidLoading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.internal_static_S2C_AndroidLoading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.class, com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.Builder.class);
    }

    public static final int ANDROIDLOADING_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString androidLoading_;
    /**
     * <code>bytes androidLoading = 1;</code>
     */
    public com.google.protobuf.ByteString getAndroidLoading() {
      return androidLoading_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!androidLoading_.isEmpty()) {
        output.writeBytes(1, androidLoading_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!androidLoading_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, androidLoading_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading)) {
        return super.equals(obj);
      }
      com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading other = (com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading) obj;

      boolean result = true;
      result = result && getAndroidLoading()
          .equals(other.getAndroidLoading());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANDROIDLOADING_FIELD_NUMBER;
      hash = (53 * hash) + getAndroidLoading().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code S2C_AndroidLoading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:S2C_AndroidLoading)
        com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.internal_static_S2C_AndroidLoading_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.internal_static_S2C_AndroidLoading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.class, com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.Builder.class);
      }

      // Construct using com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        androidLoading_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.internal_static_S2C_AndroidLoading_descriptor;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading getDefaultInstanceForType() {
        return com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.getDefaultInstance();
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading build() {
        com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading buildPartial() {
        com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading result = new com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading(this);
        result.androidLoading_ = androidLoading_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading) {
          return mergeFrom((com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading other) {
        if (other == com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading.getDefaultInstance()) return this;
        if (other.getAndroidLoading() != com.google.protobuf.ByteString.EMPTY) {
          setAndroidLoading(other.getAndroidLoading());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString androidLoading_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes androidLoading = 1;</code>
       */
      public com.google.protobuf.ByteString getAndroidLoading() {
        return androidLoading_;
      }
      /**
       * <code>bytes androidLoading = 1;</code>
       */
      public Builder setAndroidLoading(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        androidLoading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes androidLoading = 1;</code>
       */
      public Builder clearAndroidLoading() {
        
        androidLoading_ = getDefaultInstance().getAndroidLoading();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:S2C_AndroidLoading)
    }

    // @@protoc_insertion_point(class_scope:S2C_AndroidLoading)
    private static final com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading();
    }

    public static com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2C_AndroidLoading>
        PARSER = new com.google.protobuf.AbstractParser<S2C_AndroidLoading>() {
      @java.lang.Override
      public S2C_AndroidLoading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C_AndroidLoading(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C_AndroidLoading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C_AndroidLoading> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sasa5680.ProtoMessages.S2C.S2CAndroidLoading.S2C_AndroidLoading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_S2C_AndroidLoading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_S2C_AndroidLoading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030S2C_AndroidLoading.proto\",\n\022S2C_Androi" +
      "dLoading\022\026\n\016androidLoading\030\001 \001(\014B \n\036com." +
      "sasa5680.ProtoMessages.S2Cb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_S2C_AndroidLoading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_S2C_AndroidLoading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_S2C_AndroidLoading_descriptor,
        new java.lang.String[] { "AndroidLoading", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
