// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GeneralMSG.proto

package com.sasa5680.ProtoMessages;

public final class GeneralMSG {
  private GeneralMSG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GeneralOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GeneralMSG.General)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool routing = 1;</code>
     */
    boolean getRouting();

    /**
     * <code>string MessageType = 2;</code>
     */
    java.lang.String getMessageType();
    /**
     * <code>string MessageType = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getInnerMSGList();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    com.google.protobuf.Any getInnerMSG(int index);
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    int getInnerMSGCount();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getInnerMSGOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
        int index);

    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> 
        getRoutingInfoList();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index);
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    int getRoutingInfoCount();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
        getRoutingInfoOrBuilderList();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GeneralMSG.General}
   */
  public  static final class General extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GeneralMSG.General)
      GeneralOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use General.newBuilder() to construct.
    private General(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private General() {
      routing_ = false;
      messageType_ = "";
      innerMSG_ = java.util.Collections.emptyList();
      routingInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private General(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              routing_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messageType_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                innerMSG_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000004;
              }
              innerMSG_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                routingInfo_ = new java.util.ArrayList<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo>();
                mutable_bitField0_ |= 0x00000008;
              }
              routingInfo_.add(
                  input.readMessage(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          innerMSG_ = java.util.Collections.unmodifiableList(innerMSG_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          routingInfo_ = java.util.Collections.unmodifiableList(routingInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_General_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_General_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sasa5680.ProtoMessages.GeneralMSG.General.class, com.sasa5680.ProtoMessages.GeneralMSG.General.Builder.class);
    }

    private int bitField0_;
    public static final int ROUTING_FIELD_NUMBER = 1;
    private boolean routing_;
    /**
     * <code>bool routing = 1;</code>
     */
    public boolean getRouting() {
      return routing_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageType_;
    /**
     * <code>string MessageType = 2;</code>
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <code>string MessageType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INNERMSG_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.Any> innerMSG_;
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    public java.util.List<com.google.protobuf.Any> getInnerMSGList() {
      return innerMSG_;
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getInnerMSGOrBuilderList() {
      return innerMSG_;
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    public int getInnerMSGCount() {
      return innerMSG_.size();
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    public com.google.protobuf.Any getInnerMSG(int index) {
      return innerMSG_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
        int index) {
      return innerMSG_.get(index);
    }

    public static final int ROUTINGINFO_FIELD_NUMBER = 4;
    private java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> routingInfo_;
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> getRoutingInfoList() {
      return routingInfo_;
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    public java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
        getRoutingInfoOrBuilderList() {
      return routingInfo_;
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    public int getRoutingInfoCount() {
      return routingInfo_.size();
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index) {
      return routingInfo_.get(index);
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
     */
    public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
        int index) {
      return routingInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (routing_ != false) {
        output.writeBool(1, routing_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageType_);
      }
      for (int i = 0; i < innerMSG_.size(); i++) {
        output.writeMessage(3, innerMSG_.get(i));
      }
      for (int i = 0; i < routingInfo_.size(); i++) {
        output.writeMessage(4, routingInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (routing_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, routing_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageType_);
      }
      for (int i = 0; i < innerMSG_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, innerMSG_.get(i));
      }
      for (int i = 0; i < routingInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, routingInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sasa5680.ProtoMessages.GeneralMSG.General)) {
        return super.equals(obj);
      }
      com.sasa5680.ProtoMessages.GeneralMSG.General other = (com.sasa5680.ProtoMessages.GeneralMSG.General) obj;

      boolean result = true;
      result = result && (getRouting()
          == other.getRouting());
      result = result && getMessageType()
          .equals(other.getMessageType());
      result = result && getInnerMSGList()
          .equals(other.getInnerMSGList());
      result = result && getRoutingInfoList()
          .equals(other.getRoutingInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROUTING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRouting());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      if (getInnerMSGCount() > 0) {
        hash = (37 * hash) + INNERMSG_FIELD_NUMBER;
        hash = (53 * hash) + getInnerMSGList().hashCode();
      }
      if (getRoutingInfoCount() > 0) {
        hash = (37 * hash) + ROUTINGINFO_FIELD_NUMBER;
        hash = (53 * hash) + getRoutingInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.General parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sasa5680.ProtoMessages.GeneralMSG.General prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GeneralMSG.General}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GeneralMSG.General)
        com.sasa5680.ProtoMessages.GeneralMSG.GeneralOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_General_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_General_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sasa5680.ProtoMessages.GeneralMSG.General.class, com.sasa5680.ProtoMessages.GeneralMSG.General.Builder.class);
      }

      // Construct using com.sasa5680.ProtoMessages.GeneralMSG.General.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInnerMSGFieldBuilder();
          getRoutingInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        routing_ = false;

        messageType_ = "";

        if (innerMSGBuilder_ == null) {
          innerMSG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          innerMSGBuilder_.clear();
        }
        if (routingInfoBuilder_ == null) {
          routingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          routingInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_General_descriptor;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.General getDefaultInstanceForType() {
        return com.sasa5680.ProtoMessages.GeneralMSG.General.getDefaultInstance();
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.General build() {
        com.sasa5680.ProtoMessages.GeneralMSG.General result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.General buildPartial() {
        com.sasa5680.ProtoMessages.GeneralMSG.General result = new com.sasa5680.ProtoMessages.GeneralMSG.General(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.routing_ = routing_;
        result.messageType_ = messageType_;
        if (innerMSGBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            innerMSG_ = java.util.Collections.unmodifiableList(innerMSG_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.innerMSG_ = innerMSG_;
        } else {
          result.innerMSG_ = innerMSGBuilder_.build();
        }
        if (routingInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            routingInfo_ = java.util.Collections.unmodifiableList(routingInfo_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.routingInfo_ = routingInfo_;
        } else {
          result.routingInfo_ = routingInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sasa5680.ProtoMessages.GeneralMSG.General) {
          return mergeFrom((com.sasa5680.ProtoMessages.GeneralMSG.General)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sasa5680.ProtoMessages.GeneralMSG.General other) {
        if (other == com.sasa5680.ProtoMessages.GeneralMSG.General.getDefaultInstance()) return this;
        if (other.getRouting() != false) {
          setRouting(other.getRouting());
        }
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          onChanged();
        }
        if (innerMSGBuilder_ == null) {
          if (!other.innerMSG_.isEmpty()) {
            if (innerMSG_.isEmpty()) {
              innerMSG_ = other.innerMSG_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInnerMSGIsMutable();
              innerMSG_.addAll(other.innerMSG_);
            }
            onChanged();
          }
        } else {
          if (!other.innerMSG_.isEmpty()) {
            if (innerMSGBuilder_.isEmpty()) {
              innerMSGBuilder_.dispose();
              innerMSGBuilder_ = null;
              innerMSG_ = other.innerMSG_;
              bitField0_ = (bitField0_ & ~0x00000004);
              innerMSGBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInnerMSGFieldBuilder() : null;
            } else {
              innerMSGBuilder_.addAllMessages(other.innerMSG_);
            }
          }
        }
        if (routingInfoBuilder_ == null) {
          if (!other.routingInfo_.isEmpty()) {
            if (routingInfo_.isEmpty()) {
              routingInfo_ = other.routingInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRoutingInfoIsMutable();
              routingInfo_.addAll(other.routingInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.routingInfo_.isEmpty()) {
            if (routingInfoBuilder_.isEmpty()) {
              routingInfoBuilder_.dispose();
              routingInfoBuilder_ = null;
              routingInfo_ = other.routingInfo_;
              bitField0_ = (bitField0_ & ~0x00000008);
              routingInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoutingInfoFieldBuilder() : null;
            } else {
              routingInfoBuilder_.addAllMessages(other.routingInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sasa5680.ProtoMessages.GeneralMSG.General parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sasa5680.ProtoMessages.GeneralMSG.General) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean routing_ ;
      /**
       * <code>bool routing = 1;</code>
       */
      public boolean getRouting() {
        return routing_;
      }
      /**
       * <code>bool routing = 1;</code>
       */
      public Builder setRouting(boolean value) {
        
        routing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool routing = 1;</code>
       */
      public Builder clearRouting() {
        
        routing_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object messageType_ = "";
      /**
       * <code>string MessageType = 2;</code>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MessageType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MessageType = 2;</code>
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MessageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      /**
       * <code>string MessageType = 2;</code>
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> innerMSG_ =
        java.util.Collections.emptyList();
      private void ensureInnerMSGIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          innerMSG_ = new java.util.ArrayList<com.google.protobuf.Any>(innerMSG_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> innerMSGBuilder_;

      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public java.util.List<com.google.protobuf.Any> getInnerMSGList() {
        if (innerMSGBuilder_ == null) {
          return java.util.Collections.unmodifiableList(innerMSG_);
        } else {
          return innerMSGBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public int getInnerMSGCount() {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.size();
        } else {
          return innerMSGBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public com.google.protobuf.Any getInnerMSG(int index) {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.get(index);
        } else {
          return innerMSGBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder setInnerMSG(
          int index, com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.set(index, value);
          onChanged();
        } else {
          innerMSGBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder setInnerMSG(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.set(index, builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder addInnerMSG(com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.add(value);
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder addInnerMSG(
          int index, com.google.protobuf.Any value) {
        if (innerMSGBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerMSGIsMutable();
          innerMSG_.add(index, value);
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder addInnerMSG(
          com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.add(builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder addInnerMSG(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.add(index, builderForValue.build());
          onChanged();
        } else {
          innerMSGBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder addAllInnerMSG(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, innerMSG_);
          onChanged();
        } else {
          innerMSGBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder clearInnerMSG() {
        if (innerMSGBuilder_ == null) {
          innerMSG_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          innerMSGBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public Builder removeInnerMSG(int index) {
        if (innerMSGBuilder_ == null) {
          ensureInnerMSGIsMutable();
          innerMSG_.remove(index);
          onChanged();
        } else {
          innerMSGBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public com.google.protobuf.Any.Builder getInnerMSGBuilder(
          int index) {
        return getInnerMSGFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getInnerMSGOrBuilder(
          int index) {
        if (innerMSGBuilder_ == null) {
          return innerMSG_.get(index);  } else {
          return innerMSGBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getInnerMSGOrBuilderList() {
        if (innerMSGBuilder_ != null) {
          return innerMSGBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(innerMSG_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public com.google.protobuf.Any.Builder addInnerMSGBuilder() {
        return getInnerMSGFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public com.google.protobuf.Any.Builder addInnerMSGBuilder(
          int index) {
        return getInnerMSGFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Any innerMSG = 3;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getInnerMSGBuilderList() {
        return getInnerMSGFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getInnerMSGFieldBuilder() {
        if (innerMSGBuilder_ == null) {
          innerMSGBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  innerMSG_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          innerMSG_ = null;
        }
        return innerMSGBuilder_;
      }

      private java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> routingInfo_ =
        java.util.Collections.emptyList();
      private void ensureRoutingInfoIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          routingInfo_ = new java.util.ArrayList<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo>(routingInfo_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> routingInfoBuilder_;

      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> getRoutingInfoList() {
        if (routingInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingInfo_);
        } else {
          return routingInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public int getRoutingInfoCount() {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.size();
        } else {
          return routingInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index) {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.get(index);
        } else {
          return routingInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder setRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.set(index, value);
          onChanged();
        } else {
          routingInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder setRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder addRoutingInfo(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.add(value);
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder addRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.add(index, value);
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder addRoutingInfo(
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.add(builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder addRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder addAllRoutingInfo(
          java.lang.Iterable<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> values) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routingInfo_);
          onChanged();
        } else {
          routingInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder clearRoutingInfo() {
        if (routingInfoBuilder_ == null) {
          routingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          routingInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public Builder removeRoutingInfo(int index) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.remove(index);
          onChanged();
        } else {
          routingInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder getRoutingInfoBuilder(
          int index) {
        return getRoutingInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
          int index) {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.get(index);  } else {
          return routingInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
           getRoutingInfoOrBuilderList() {
        if (routingInfoBuilder_ != null) {
          return routingInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingInfo_);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder addRoutingInfoBuilder() {
        return getRoutingInfoFieldBuilder().addBuilder(
            com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder addRoutingInfoBuilder(
          int index) {
        return getRoutingInfoFieldBuilder().addBuilder(
            index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 4;</code>
       */
      public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder> 
           getRoutingInfoBuilderList() {
        return getRoutingInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
          getRoutingInfoFieldBuilder() {
        if (routingInfoBuilder_ == null) {
          routingInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder>(
                  routingInfo_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          routingInfo_ = null;
        }
        return routingInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GeneralMSG.General)
    }

    // @@protoc_insertion_point(class_scope:GeneralMSG.General)
    private static final com.sasa5680.ProtoMessages.GeneralMSG.General DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sasa5680.ProtoMessages.GeneralMSG.General();
    }

    public static com.sasa5680.ProtoMessages.GeneralMSG.General getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<General>
        PARSER = new com.google.protobuf.AbstractParser<General>() {
      @java.lang.Override
      public General parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new General(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<General> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<General> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sasa5680.ProtoMessages.GeneralMSG.General getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoutingInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GeneralMSG.RoutingInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string senderID = 1;</code>
     */
    java.lang.String getSenderID();
    /**
     * <code>string senderID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderIDBytes();

    /**
     * <code>string senderType = 2;</code>
     */
    java.lang.String getSenderType();
    /**
     * <code>string senderType = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderTypeBytes();

    /**
     * <code>string destinationId = 3;</code>
     */
    java.lang.String getDestinationId();
    /**
     * <code>string destinationId = 3;</code>
     */
    com.google.protobuf.ByteString
        getDestinationIdBytes();

    /**
     * <code>string destinationType = 4;</code>
     */
    java.lang.String getDestinationType();
    /**
     * <code>string destinationType = 4;</code>
     */
    com.google.protobuf.ByteString
        getDestinationTypeBytes();
  }
  /**
   * Protobuf type {@code GeneralMSG.RoutingInfo}
   */
  public  static final class RoutingInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GeneralMSG.RoutingInfo)
      RoutingInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoutingInfo.newBuilder() to construct.
    private RoutingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoutingInfo() {
      senderID_ = "";
      senderType_ = "";
      destinationId_ = "";
      destinationType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoutingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              senderID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              senderType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              destinationId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              destinationType_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_RoutingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_RoutingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.class, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder.class);
    }

    public static final int SENDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object senderID_;
    /**
     * <code>string senderID = 1;</code>
     */
    public java.lang.String getSenderID() {
      java.lang.Object ref = senderID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderID_ = s;
        return s;
      }
    }
    /**
     * <code>string senderID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIDBytes() {
      java.lang.Object ref = senderID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDERTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object senderType_;
    /**
     * <code>string senderType = 2;</code>
     */
    public java.lang.String getSenderType() {
      java.lang.Object ref = senderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderType_ = s;
        return s;
      }
    }
    /**
     * <code>string senderType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderTypeBytes() {
      java.lang.Object ref = senderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONID_FIELD_NUMBER = 3;
    private volatile java.lang.Object destinationId_;
    /**
     * <code>string destinationId = 3;</code>
     */
    public java.lang.String getDestinationId() {
      java.lang.Object ref = destinationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationId_ = s;
        return s;
      }
    }
    /**
     * <code>string destinationId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationIdBytes() {
      java.lang.Object ref = destinationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATIONTYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object destinationType_;
    /**
     * <code>string destinationType = 4;</code>
     */
    public java.lang.String getDestinationType() {
      java.lang.Object ref = destinationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationType_ = s;
        return s;
      }
    }
    /**
     * <code>string destinationType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationTypeBytes() {
      java.lang.Object ref = destinationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderID_);
      }
      if (!getSenderTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderType_);
      }
      if (!getDestinationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, destinationId_);
      }
      if (!getDestinationTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destinationType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderID_);
      }
      if (!getSenderTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderType_);
      }
      if (!getDestinationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, destinationId_);
      }
      if (!getDestinationTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destinationType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo)) {
        return super.equals(obj);
      }
      com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo other = (com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo) obj;

      boolean result = true;
      result = result && getSenderID()
          .equals(other.getSenderID());
      result = result && getSenderType()
          .equals(other.getSenderType());
      result = result && getDestinationId()
          .equals(other.getDestinationId());
      result = result && getDestinationType()
          .equals(other.getDestinationType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDERID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderID().hashCode();
      hash = (37 * hash) + SENDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSenderType().hashCode();
      hash = (37 * hash) + DESTINATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationId().hashCode();
      hash = (37 * hash) + DESTINATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GeneralMSG.RoutingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GeneralMSG.RoutingInfo)
        com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_RoutingInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_RoutingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.class, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder.class);
      }

      // Construct using com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        senderID_ = "";

        senderType_ = "";

        destinationId_ = "";

        destinationType_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sasa5680.ProtoMessages.GeneralMSG.internal_static_GeneralMSG_RoutingInfo_descriptor;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getDefaultInstanceForType() {
        return com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo build() {
        com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo buildPartial() {
        com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo result = new com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo(this);
        result.senderID_ = senderID_;
        result.senderType_ = senderType_;
        result.destinationId_ = destinationId_;
        result.destinationType_ = destinationType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo) {
          return mergeFrom((com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo other) {
        if (other == com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance()) return this;
        if (!other.getSenderID().isEmpty()) {
          senderID_ = other.senderID_;
          onChanged();
        }
        if (!other.getSenderType().isEmpty()) {
          senderType_ = other.senderType_;
          onChanged();
        }
        if (!other.getDestinationId().isEmpty()) {
          destinationId_ = other.destinationId_;
          onChanged();
        }
        if (!other.getDestinationType().isEmpty()) {
          destinationType_ = other.destinationType_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object senderID_ = "";
      /**
       * <code>string senderID = 1;</code>
       */
      public java.lang.String getSenderID() {
        java.lang.Object ref = senderID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIDBytes() {
        java.lang.Object ref = senderID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderID = 1;</code>
       */
      public Builder setSenderID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderID = 1;</code>
       */
      public Builder clearSenderID() {
        
        senderID_ = getDefaultInstance().getSenderID();
        onChanged();
        return this;
      }
      /**
       * <code>string senderID = 1;</code>
       */
      public Builder setSenderIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senderType_ = "";
      /**
       * <code>string senderType = 2;</code>
       */
      public java.lang.String getSenderType() {
        java.lang.Object ref = senderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senderType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderTypeBytes() {
        java.lang.Object ref = senderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senderType = 2;</code>
       */
      public Builder setSenderType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senderType = 2;</code>
       */
      public Builder clearSenderType() {
        
        senderType_ = getDefaultInstance().getSenderType();
        onChanged();
        return this;
      }
      /**
       * <code>string senderType = 2;</code>
       */
      public Builder setSenderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senderType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destinationId_ = "";
      /**
       * <code>string destinationId = 3;</code>
       */
      public java.lang.String getDestinationId() {
        java.lang.Object ref = destinationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destinationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destinationId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationIdBytes() {
        java.lang.Object ref = destinationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destinationId = 3;</code>
       */
      public Builder setDestinationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destinationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destinationId = 3;</code>
       */
      public Builder clearDestinationId() {
        
        destinationId_ = getDefaultInstance().getDestinationId();
        onChanged();
        return this;
      }
      /**
       * <code>string destinationId = 3;</code>
       */
      public Builder setDestinationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destinationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object destinationType_ = "";
      /**
       * <code>string destinationType = 4;</code>
       */
      public java.lang.String getDestinationType() {
        java.lang.Object ref = destinationType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          destinationType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string destinationType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationTypeBytes() {
        java.lang.Object ref = destinationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destinationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destinationType = 4;</code>
       */
      public Builder setDestinationType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destinationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destinationType = 4;</code>
       */
      public Builder clearDestinationType() {
        
        destinationType_ = getDefaultInstance().getDestinationType();
        onChanged();
        return this;
      }
      /**
       * <code>string destinationType = 4;</code>
       */
      public Builder setDestinationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destinationType_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GeneralMSG.RoutingInfo)
    }

    // @@protoc_insertion_point(class_scope:GeneralMSG.RoutingInfo)
    private static final com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo();
    }

    public static com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoutingInfo>
        PARSER = new com.google.protobuf.AbstractParser<RoutingInfo>() {
      @java.lang.Override
      public RoutingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoutingInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoutingInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoutingInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeneralMSG_General_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeneralMSG_General_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GeneralMSG_RoutingInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GeneralMSG_RoutingInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020GeneralMSG.proto\022\nGeneralMSG\032\031google/p" +
      "rotobuf/any.proto\"\205\001\n\007General\022\017\n\007routing" +
      "\030\001 \001(\010\022\023\n\013MessageType\030\002 \001(\t\022&\n\010innerMSG\030" +
      "\003 \003(\0132\024.google.protobuf.Any\022,\n\013routingIn" +
      "fo\030\004 \003(\0132\027.GeneralMSG.RoutingInfo\"c\n\013Rou" +
      "tingInfo\022\020\n\010senderID\030\001 \001(\t\022\022\n\nsenderType" +
      "\030\002 \001(\t\022\025\n\rdestinationId\030\003 \001(\t\022\027\n\017destina" +
      "tionType\030\004 \001(\tB\034\n\032com.sasa5680.ProtoMess" +
      "agesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_GeneralMSG_General_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GeneralMSG_General_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeneralMSG_General_descriptor,
        new java.lang.String[] { "Routing", "MessageType", "InnerMSG", "RoutingInfo", });
    internal_static_GeneralMSG_RoutingInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GeneralMSG_RoutingInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GeneralMSG_RoutingInfo_descriptor,
        new java.lang.String[] { "SenderID", "SenderType", "DestinationId", "DestinationType", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
