// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A2R_DroneControl.proto

package com.sasa5680.ProtoMessages.A2R;

public final class A2RDroneControl {
  private A2RDroneControl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface A2R_DroneControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:A2R_DroneControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool Roll_L = 1;</code>
     */
    boolean getRollL();

    /**
     * <code>bool Roll_R = 2;</code>
     */
    boolean getRollR();

    /**
     * <code>bool Pitch_F = 3;</code>
     */
    boolean getPitchF();

    /**
     * <code>bool Pitch_B = 4;</code>
     */
    boolean getPitchB();

    /**
     * <code>bool Yaw_CW = 5;</code>
     */
    boolean getYawCW();

    /**
     * <code>bool Yaw_CCW = 6;</code>
     */
    boolean getYawCCW();

    /**
     * <code>bool Throttle_UP = 7;</code>
     */
    boolean getThrottleUP();

    /**
     * <code>bool Throttle_Down = 8;</code>
     */
    boolean getThrottleDown();

    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> 
        getRoutingInfoList();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index);
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    int getRoutingInfoCount();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
        getRoutingInfoOrBuilderList();
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code A2R_DroneControl}
   */
  public  static final class A2R_DroneControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:A2R_DroneControl)
      A2R_DroneControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use A2R_DroneControl.newBuilder() to construct.
    private A2R_DroneControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private A2R_DroneControl() {
      rollL_ = false;
      rollR_ = false;
      pitchF_ = false;
      pitchB_ = false;
      yawCW_ = false;
      yawCCW_ = false;
      throttleUP_ = false;
      throttleDown_ = false;
      routingInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private A2R_DroneControl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rollL_ = input.readBool();
              break;
            }
            case 16: {

              rollR_ = input.readBool();
              break;
            }
            case 24: {

              pitchF_ = input.readBool();
              break;
            }
            case 32: {

              pitchB_ = input.readBool();
              break;
            }
            case 40: {

              yawCW_ = input.readBool();
              break;
            }
            case 48: {

              yawCCW_ = input.readBool();
              break;
            }
            case 56: {

              throttleUP_ = input.readBool();
              break;
            }
            case 64: {

              throttleDown_ = input.readBool();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                routingInfo_ = new java.util.ArrayList<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo>();
                mutable_bitField0_ |= 0x00000100;
              }
              routingInfo_.add(
                  input.readMessage(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          routingInfo_ = java.util.Collections.unmodifiableList(routingInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.internal_static_A2R_DroneControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.internal_static_A2R_DroneControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.class, com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.Builder.class);
    }

    private int bitField0_;
    public static final int ROLL_L_FIELD_NUMBER = 1;
    private boolean rollL_;
    /**
     * <code>bool Roll_L = 1;</code>
     */
    public boolean getRollL() {
      return rollL_;
    }

    public static final int ROLL_R_FIELD_NUMBER = 2;
    private boolean rollR_;
    /**
     * <code>bool Roll_R = 2;</code>
     */
    public boolean getRollR() {
      return rollR_;
    }

    public static final int PITCH_F_FIELD_NUMBER = 3;
    private boolean pitchF_;
    /**
     * <code>bool Pitch_F = 3;</code>
     */
    public boolean getPitchF() {
      return pitchF_;
    }

    public static final int PITCH_B_FIELD_NUMBER = 4;
    private boolean pitchB_;
    /**
     * <code>bool Pitch_B = 4;</code>
     */
    public boolean getPitchB() {
      return pitchB_;
    }

    public static final int YAW_CW_FIELD_NUMBER = 5;
    private boolean yawCW_;
    /**
     * <code>bool Yaw_CW = 5;</code>
     */
    public boolean getYawCW() {
      return yawCW_;
    }

    public static final int YAW_CCW_FIELD_NUMBER = 6;
    private boolean yawCCW_;
    /**
     * <code>bool Yaw_CCW = 6;</code>
     */
    public boolean getYawCCW() {
      return yawCCW_;
    }

    public static final int THROTTLE_UP_FIELD_NUMBER = 7;
    private boolean throttleUP_;
    /**
     * <code>bool Throttle_UP = 7;</code>
     */
    public boolean getThrottleUP() {
      return throttleUP_;
    }

    public static final int THROTTLE_DOWN_FIELD_NUMBER = 8;
    private boolean throttleDown_;
    /**
     * <code>bool Throttle_Down = 8;</code>
     */
    public boolean getThrottleDown() {
      return throttleDown_;
    }

    public static final int ROUTINGINFO_FIELD_NUMBER = 9;
    private java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> routingInfo_;
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> getRoutingInfoList() {
      return routingInfo_;
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    public java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
        getRoutingInfoOrBuilderList() {
      return routingInfo_;
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    public int getRoutingInfoCount() {
      return routingInfo_.size();
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index) {
      return routingInfo_.get(index);
    }
    /**
     * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
     */
    public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
        int index) {
      return routingInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rollL_ != false) {
        output.writeBool(1, rollL_);
      }
      if (rollR_ != false) {
        output.writeBool(2, rollR_);
      }
      if (pitchF_ != false) {
        output.writeBool(3, pitchF_);
      }
      if (pitchB_ != false) {
        output.writeBool(4, pitchB_);
      }
      if (yawCW_ != false) {
        output.writeBool(5, yawCW_);
      }
      if (yawCCW_ != false) {
        output.writeBool(6, yawCCW_);
      }
      if (throttleUP_ != false) {
        output.writeBool(7, throttleUP_);
      }
      if (throttleDown_ != false) {
        output.writeBool(8, throttleDown_);
      }
      for (int i = 0; i < routingInfo_.size(); i++) {
        output.writeMessage(9, routingInfo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rollL_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, rollL_);
      }
      if (rollR_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, rollR_);
      }
      if (pitchF_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, pitchF_);
      }
      if (pitchB_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, pitchB_);
      }
      if (yawCW_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, yawCW_);
      }
      if (yawCCW_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, yawCCW_);
      }
      if (throttleUP_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, throttleUP_);
      }
      if (throttleDown_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, throttleDown_);
      }
      for (int i = 0; i < routingInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, routingInfo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl)) {
        return super.equals(obj);
      }
      com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl other = (com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl) obj;

      boolean result = true;
      result = result && (getRollL()
          == other.getRollL());
      result = result && (getRollR()
          == other.getRollR());
      result = result && (getPitchF()
          == other.getPitchF());
      result = result && (getPitchB()
          == other.getPitchB());
      result = result && (getYawCW()
          == other.getYawCW());
      result = result && (getYawCCW()
          == other.getYawCCW());
      result = result && (getThrottleUP()
          == other.getThrottleUP());
      result = result && (getThrottleDown()
          == other.getThrottleDown());
      result = result && getRoutingInfoList()
          .equals(other.getRoutingInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROLL_L_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRollL());
      hash = (37 * hash) + ROLL_R_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRollR());
      hash = (37 * hash) + PITCH_F_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPitchF());
      hash = (37 * hash) + PITCH_B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPitchB());
      hash = (37 * hash) + YAW_CW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getYawCW());
      hash = (37 * hash) + YAW_CCW_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getYawCCW());
      hash = (37 * hash) + THROTTLE_UP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getThrottleUP());
      hash = (37 * hash) + THROTTLE_DOWN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getThrottleDown());
      if (getRoutingInfoCount() > 0) {
        hash = (37 * hash) + ROUTINGINFO_FIELD_NUMBER;
        hash = (53 * hash) + getRoutingInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code A2R_DroneControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:A2R_DroneControl)
        com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.internal_static_A2R_DroneControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.internal_static_A2R_DroneControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.class, com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.Builder.class);
      }

      // Construct using com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRoutingInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rollL_ = false;

        rollR_ = false;

        pitchF_ = false;

        pitchB_ = false;

        yawCW_ = false;

        yawCCW_ = false;

        throttleUP_ = false;

        throttleDown_ = false;

        if (routingInfoBuilder_ == null) {
          routingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          routingInfoBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.internal_static_A2R_DroneControl_descriptor;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl getDefaultInstanceForType() {
        return com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.getDefaultInstance();
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl build() {
        com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl buildPartial() {
        com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl result = new com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.rollL_ = rollL_;
        result.rollR_ = rollR_;
        result.pitchF_ = pitchF_;
        result.pitchB_ = pitchB_;
        result.yawCW_ = yawCW_;
        result.yawCCW_ = yawCCW_;
        result.throttleUP_ = throttleUP_;
        result.throttleDown_ = throttleDown_;
        if (routingInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            routingInfo_ = java.util.Collections.unmodifiableList(routingInfo_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.routingInfo_ = routingInfo_;
        } else {
          result.routingInfo_ = routingInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl) {
          return mergeFrom((com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl other) {
        if (other == com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl.getDefaultInstance()) return this;
        if (other.getRollL() != false) {
          setRollL(other.getRollL());
        }
        if (other.getRollR() != false) {
          setRollR(other.getRollR());
        }
        if (other.getPitchF() != false) {
          setPitchF(other.getPitchF());
        }
        if (other.getPitchB() != false) {
          setPitchB(other.getPitchB());
        }
        if (other.getYawCW() != false) {
          setYawCW(other.getYawCW());
        }
        if (other.getYawCCW() != false) {
          setYawCCW(other.getYawCCW());
        }
        if (other.getThrottleUP() != false) {
          setThrottleUP(other.getThrottleUP());
        }
        if (other.getThrottleDown() != false) {
          setThrottleDown(other.getThrottleDown());
        }
        if (routingInfoBuilder_ == null) {
          if (!other.routingInfo_.isEmpty()) {
            if (routingInfo_.isEmpty()) {
              routingInfo_ = other.routingInfo_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureRoutingInfoIsMutable();
              routingInfo_.addAll(other.routingInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.routingInfo_.isEmpty()) {
            if (routingInfoBuilder_.isEmpty()) {
              routingInfoBuilder_.dispose();
              routingInfoBuilder_ = null;
              routingInfo_ = other.routingInfo_;
              bitField0_ = (bitField0_ & ~0x00000100);
              routingInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRoutingInfoFieldBuilder() : null;
            } else {
              routingInfoBuilder_.addAllMessages(other.routingInfo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean rollL_ ;
      /**
       * <code>bool Roll_L = 1;</code>
       */
      public boolean getRollL() {
        return rollL_;
      }
      /**
       * <code>bool Roll_L = 1;</code>
       */
      public Builder setRollL(boolean value) {
        
        rollL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Roll_L = 1;</code>
       */
      public Builder clearRollL() {
        
        rollL_ = false;
        onChanged();
        return this;
      }

      private boolean rollR_ ;
      /**
       * <code>bool Roll_R = 2;</code>
       */
      public boolean getRollR() {
        return rollR_;
      }
      /**
       * <code>bool Roll_R = 2;</code>
       */
      public Builder setRollR(boolean value) {
        
        rollR_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Roll_R = 2;</code>
       */
      public Builder clearRollR() {
        
        rollR_ = false;
        onChanged();
        return this;
      }

      private boolean pitchF_ ;
      /**
       * <code>bool Pitch_F = 3;</code>
       */
      public boolean getPitchF() {
        return pitchF_;
      }
      /**
       * <code>bool Pitch_F = 3;</code>
       */
      public Builder setPitchF(boolean value) {
        
        pitchF_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Pitch_F = 3;</code>
       */
      public Builder clearPitchF() {
        
        pitchF_ = false;
        onChanged();
        return this;
      }

      private boolean pitchB_ ;
      /**
       * <code>bool Pitch_B = 4;</code>
       */
      public boolean getPitchB() {
        return pitchB_;
      }
      /**
       * <code>bool Pitch_B = 4;</code>
       */
      public Builder setPitchB(boolean value) {
        
        pitchB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Pitch_B = 4;</code>
       */
      public Builder clearPitchB() {
        
        pitchB_ = false;
        onChanged();
        return this;
      }

      private boolean yawCW_ ;
      /**
       * <code>bool Yaw_CW = 5;</code>
       */
      public boolean getYawCW() {
        return yawCW_;
      }
      /**
       * <code>bool Yaw_CW = 5;</code>
       */
      public Builder setYawCW(boolean value) {
        
        yawCW_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Yaw_CW = 5;</code>
       */
      public Builder clearYawCW() {
        
        yawCW_ = false;
        onChanged();
        return this;
      }

      private boolean yawCCW_ ;
      /**
       * <code>bool Yaw_CCW = 6;</code>
       */
      public boolean getYawCCW() {
        return yawCCW_;
      }
      /**
       * <code>bool Yaw_CCW = 6;</code>
       */
      public Builder setYawCCW(boolean value) {
        
        yawCCW_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Yaw_CCW = 6;</code>
       */
      public Builder clearYawCCW() {
        
        yawCCW_ = false;
        onChanged();
        return this;
      }

      private boolean throttleUP_ ;
      /**
       * <code>bool Throttle_UP = 7;</code>
       */
      public boolean getThrottleUP() {
        return throttleUP_;
      }
      /**
       * <code>bool Throttle_UP = 7;</code>
       */
      public Builder setThrottleUP(boolean value) {
        
        throttleUP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Throttle_UP = 7;</code>
       */
      public Builder clearThrottleUP() {
        
        throttleUP_ = false;
        onChanged();
        return this;
      }

      private boolean throttleDown_ ;
      /**
       * <code>bool Throttle_Down = 8;</code>
       */
      public boolean getThrottleDown() {
        return throttleDown_;
      }
      /**
       * <code>bool Throttle_Down = 8;</code>
       */
      public Builder setThrottleDown(boolean value) {
        
        throttleDown_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Throttle_Down = 8;</code>
       */
      public Builder clearThrottleDown() {
        
        throttleDown_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> routingInfo_ =
        java.util.Collections.emptyList();
      private void ensureRoutingInfoIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          routingInfo_ = new java.util.ArrayList<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo>(routingInfo_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> routingInfoBuilder_;

      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> getRoutingInfoList() {
        if (routingInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routingInfo_);
        } else {
          return routingInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public int getRoutingInfoCount() {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.size();
        } else {
          return routingInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo getRoutingInfo(int index) {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.get(index);
        } else {
          return routingInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder setRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.set(index, value);
          onChanged();
        } else {
          routingInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder setRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder addRoutingInfo(com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.add(value);
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder addRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo value) {
        if (routingInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRoutingInfoIsMutable();
          routingInfo_.add(index, value);
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder addRoutingInfo(
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.add(builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder addRoutingInfo(
          int index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder builderForValue) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          routingInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder addAllRoutingInfo(
          java.lang.Iterable<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo> values) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routingInfo_);
          onChanged();
        } else {
          routingInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder clearRoutingInfo() {
        if (routingInfoBuilder_ == null) {
          routingInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          routingInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public Builder removeRoutingInfo(int index) {
        if (routingInfoBuilder_ == null) {
          ensureRoutingInfoIsMutable();
          routingInfo_.remove(index);
          onChanged();
        } else {
          routingInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder getRoutingInfoBuilder(
          int index) {
        return getRoutingInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder getRoutingInfoOrBuilder(
          int index) {
        if (routingInfoBuilder_ == null) {
          return routingInfo_.get(index);  } else {
          return routingInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public java.util.List<? extends com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
           getRoutingInfoOrBuilderList() {
        if (routingInfoBuilder_ != null) {
          return routingInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routingInfo_);
        }
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder addRoutingInfoBuilder() {
        return getRoutingInfoFieldBuilder().addBuilder(
            com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder addRoutingInfoBuilder(
          int index) {
        return getRoutingInfoFieldBuilder().addBuilder(
            index, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .GeneralMSG.RoutingInfo routingInfo = 9;</code>
       */
      public java.util.List<com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder> 
           getRoutingInfoBuilderList() {
        return getRoutingInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder> 
          getRoutingInfoFieldBuilder() {
        if (routingInfoBuilder_ == null) {
          routingInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfo.Builder, com.sasa5680.ProtoMessages.GeneralMSG.RoutingInfoOrBuilder>(
                  routingInfo_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          routingInfo_ = null;
        }
        return routingInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:A2R_DroneControl)
    }

    // @@protoc_insertion_point(class_scope:A2R_DroneControl)
    private static final com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl();
    }

    public static com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<A2R_DroneControl>
        PARSER = new com.google.protobuf.AbstractParser<A2R_DroneControl>() {
      @java.lang.Override
      public A2R_DroneControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new A2R_DroneControl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<A2R_DroneControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<A2R_DroneControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sasa5680.ProtoMessages.A2R.A2RDroneControl.A2R_DroneControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_A2R_DroneControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_A2R_DroneControl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026A2R_DroneControl.proto\032\020GeneralMSG.pro" +
      "to\"\317\001\n\020A2R_DroneControl\022\016\n\006Roll_L\030\001 \001(\010\022" +
      "\016\n\006Roll_R\030\002 \001(\010\022\017\n\007Pitch_F\030\003 \001(\010\022\017\n\007Pitc" +
      "h_B\030\004 \001(\010\022\016\n\006Yaw_CW\030\005 \001(\010\022\017\n\007Yaw_CCW\030\006 \001" +
      "(\010\022\023\n\013Throttle_UP\030\007 \001(\010\022\025\n\rThrottle_Down" +
      "\030\010 \001(\010\022,\n\013routingInfo\030\t \003(\0132\027.GeneralMSG" +
      ".RoutingInfoB \n\036com.sasa5680.ProtoMessag" +
      "es.A2Rb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sasa5680.ProtoMessages.GeneralMSG.getDescriptor(),
        }, assigner);
    internal_static_A2R_DroneControl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_A2R_DroneControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_A2R_DroneControl_descriptor,
        new java.lang.String[] { "RollL", "RollR", "PitchF", "PitchB", "YawCW", "YawCCW", "ThrottleUP", "ThrottleDown", "RoutingInfo", });
    com.sasa5680.ProtoMessages.GeneralMSG.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
